version: '3.7'
services:
  app:
    image: 'brsrker/emerald-jwt-auth:v1.0.0'
    restart: always
    volumes:
      - './temp'
    environment:
      - POSTGRES_DB=jdbc:postgresql://postgres_dev:5432/emerald-jwt-auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '61100:61100'
    networks:
      - default

networks:
  default:
    external: true
    name: brsrker